#!/bin/bash

TESTS_REPO_OWNER="${TESTS_REPO_OWNER:-AnastasiiaASD}"
TESTS_REPO_NAME="${TESTS_REPO_NAME:-revyoos-qa-automation}"

if [ -z "$GH_TOKEN" ]; then
    echo "ERROR: GH_TOKEN not set" >&2; exit 1
fi

TESTS_REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${TESTS_REPO_OWNER}/${TESTS_REPO_NAME}.git"

: "${OPENCODE_MODEL_ANALYZE:=opencode-go/deepseek-v4-flash}"
: "${OPENCODE_MODEL_WRITE:=opencode-go/qwen3.6-plus}"

prefetch_task_details() {
    local task_id="$1"
    mkdir -p /app/tmp
    local out="/app/tmp/${task_id}_details.txt"
    if jira-ai task-with-details "$task_id" > "$out" 2>/dev/null; then
        echo "Cached: $out ($(wc -c < "$out") bytes)"
    else
        echo "WARN: prefetch failed for $task_id" >&2; rm -f "$out"
    fi
}

# ── Phase 1: analyze ────────────────────────────────────────────────────────
echo "=== Phase 1: analyze ==="
OUTPUT=$(jira-ai run-jql "assignee = currentUser() AND status = 'Prep Autotests' AND labels NOT IN (analyzed)" --limit 1)
TASK_ID=$(echo "$OUTPUT" | grep "│" | grep -v "Key" | awk -F '│' '{print $2}' | tr -d '[:space:]')

if [ -n "$TASK_ID" ]; then
    echo "→ $TASK_ID (model: $OPENCODE_MODEL_ANALYZE)"
    prefetch_task_details "$TASK_ID"
    opencode run "Please run @/instructions/analyze-task.md for $TASK_ID. Details at /app/tmp/${TASK_ID}_details.txt" \
        --model "$OPENCODE_MODEL_ANALYZE"
    rm -f "/app/tmp/${TASK_ID}_details.txt"
    exit 0
fi

# ── Phase 2: test-scenarios ──────────────────────────────────────────────────
echo "=== Phase 2: test-scenarios ==="
OUTPUT=$(jira-ai run-jql "assignee = currentUser() AND status = 'Prep Autotests' AND labels = analyzed AND labels NOT IN (scenarios-done)" --limit 1)
TASK_ID=$(echo "$OUTPUT" | grep "│" | grep -v "Key" | awk -F '│' '{print $2}' | tr -d '[:space:]')

if [ -n "$TASK_ID" ]; then
    echo "→ $TASK_ID (model: $OPENCODE_MODEL_ANALYZE)"
    prefetch_task_details "$TASK_ID"
    opencode run "Please run @/instructions/test-scenarios.md for $TASK_ID. Details at /app/tmp/${TASK_ID}_details.txt" \
        --model "$OPENCODE_MODEL_ANALYZE"
    rm -f "/app/tmp/${TASK_ID}_details.txt"
    exit 0
fi

# ── Phase 3: write-tests ─────────────────────────────────────────────────────
echo "=== Phase 3: write-tests ==="
OUTPUT=$(jira-ai run-jql "assignee = currentUser() AND status = 'Prep Autotests' AND labels = scenarios-done AND labels NOT IN (pr_created)" --limit 1)
TASK_ID=$(echo "$OUTPUT" | grep "│" | grep -v "Key" | awk -F '│' '{print $2}' | tr -d '[:space:]')

if [ -n "$TASK_ID" ]; then
    echo "→ $TASK_ID (write: $OPENCODE_MODEL_WRITE)"
    prefetch_task_details "$TASK_ID"

    BRANCH="tests/${TASK_ID}"

    # Клонуємо репо
    rm -rf /app/repo
    git clone "$TESTS_REPO_URL" /app/repo
    cd /app/repo && npm install && cd -
    ln -sfn /app/instructions /app/repo/instructions

    # Запускаємо write-tests
    (cd /app && opencode run "Please run @/instructions/write-tests.md for $TASK_ID. Details at /app/tmp/${TASK_ID}_details.txt" \
        --model "$OPENCODE_MODEL_WRITE")

    # Push + PR
    pushd /app/repo > /dev/null
    git remote set-url origin "$TESTS_REPO_URL" 2>/dev/null || git remote add origin "$TESTS_REPO_URL"

    if git rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
        git push -u origin "$BRANCH"

        PR_RESPONSE=$(curl -sS \
            -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${TESTS_REPO_OWNER}/${TESTS_REPO_NAME}/pulls" \
            -d "{\"title\":\"${TASK_ID}: автотести\",\"head\":\"${BRANCH}\",\"base\":\"main\",\"body\":\"Auto-generated by Reviz for ${TASK_ID}\"}")

        PR_URL=$(echo "$PR_RESPONSE" | grep -o '"html_url":"[^"]*pulls/[0-9]*"' | head -1 | cut -d'"' -f4)

        if [ -n "$PR_URL" ]; then
            echo "PR created: $PR_URL"

            # Коментар у Jira з посиланням на PR
            cat > "/app/tmp/${TASK_ID}_pr_comment.md" <<EOF
🤖 Reviz написав автотести та створив PR: ${PR_URL}

Гілка: \`${BRANCH}\`
Папка тестів: \`tests/${TASK_ID}/\`

GitHub Actions запустить тести автоматично після відкриття PR.

— 🤖 Reviz AI Agent
EOF
            jira-ai add-comment --file-path "/app/tmp/${TASK_ID}_pr_comment.md" --issue-key "$TASK_ID"
            rm -f "/app/tmp/${TASK_ID}_pr_comment.md"
        else
            echo "WARN: PR URL not parsed. Response: $PR_RESPONSE" >&2
        fi

        # Лейбла тільки після успішного пушу + PR
        jira-ai add-label-to-issue "$TASK_ID" pr_created
    else
        echo "ERROR: branch ${BRANCH} not created by opencode — skipping push/PR" >&2
    fi
    popd > /dev/null

    rm -f "/app/tmp/${TASK_ID}_details.txt"
    rm -rf /app/repo
    exit 0
fi

# ── Phase 4: retest ──────────────────────────────────────────────────────────
echo "=== Phase 4: retest ==="
OUTPUT=$(jira-ai run-jql "assignee = currentUser() AND status = 'Ready for Retest' AND labels NOT IN (retested)" --limit 1)
TASK_ID=$(echo "$OUTPUT" | grep "│" | grep -v "Key" | awk -F '│' '{print $2}' | tr -d '[:space:]')

if [ -n "$TASK_ID" ]; then
    echo "→ $TASK_ID (model: $OPENCODE_MODEL_ANALYZE)"
    prefetch_task_details "$TASK_ID"
    opencode run "Please run @/instructions/retest.md for $TASK_ID. Details at /app/tmp/${TASK_ID}_details.txt" \
        --model "$OPENCODE_MODEL_ANALYZE"
    rm -f "/app/tmp/${TASK_ID}_details.txt"
    exit 0
fi

echo "No tasks found in any phase."
